# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-29 09:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playerchampionmastery',
            unique_together=set([('summoner', 'champion')]),
        ),
    ]
