# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-29 09:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20160429_0557'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='player',
            unique_together=set([('summoner_id', 'region')]),
        ),
    ]
