# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-29 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20160429_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerchampionmastery',
            name='champion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Champion'),
        ),
        migrations.AlterField(
            model_name='playerchampionmastery',
            name='summoner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Player'),
        ),
    ]
